[package]
name = "nano-dm"
version = "0.1.0"
authors = ["Kevin Mehall <km@kevinmehall.net>"]

[dependencies]
libusb = { git="https://github.com/kevinmehall/libusb-rs.git", rev="6a88815888463dcd11cade340cdb23b8ee6de853" }
